// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5nUDCMGXtKJ3tgbqLdIEBSwPnU3uBwPk',
    appId: '1:911601510348:web:8512bacf0848407fe29f69',
    messagingSenderId: '911601510348',
    projectId: 'acepick-mvp',
    authDomain: 'acepick-mvp.firebaseapp.com',
    storageBucket: 'acepick-mvp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoUMHKYdGcBix2Et1iL7VQHHKrcRII61I',
    appId: '1:911601510348:android:8a1afacb848796e5e29f69',
    messagingSenderId: '911601510348',
    projectId: 'acepick-mvp',
    storageBucket: 'acepick-mvp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_dPXyo-McdRcAmznF5wgKRaOfb8-psqg',
    appId: '1:911601510348:ios:a609ddf26bf72174e29f69',
    messagingSenderId: '911601510348',
    projectId: 'acepick-mvp',
    storageBucket: 'acepick-mvp.firebasestorage.app',
    iosBundleId: 'com.acepick.acepick',
  );
}
